### PR TITLE
Partial fix for paths with spaces

### PR DESCRIPTION
**Pull request by luispedro**
Still not working because `run_FragGeneScan.pl` fails, but that seems to be a very thin wrapper around `FragGeneScan` and calling `FragGeneScan` directly works. So, either (1) call `FragGeneScan` directly or (2) fix `run_FragGeneScan.pl`

I also removed the use of `multiprocessing` as it was incompletely implemented. In particular, it was not correctly propagating exceptions past the `Pool.apply_async` call. As it is not a big deal (this whole step is 2 minutes or so and can probably be a bit trimmed down too), I didn't feel it was worthwhile to spend the time implementing it properly.

### CODE REVIEW

**Comment by psj1997** [comment]
For multiprocessing, it is meaningful when multi_sample binning mode. For about 100 samples, with multiprocessing, it takes several hours compared to several days without multiprocessing.

**Comment by luispedro** [comment]
> For multiprocessing, it is meaningful when multi_sample binning mode. For about 100 samples, with multiprocessing, it takes several hours compared to several days without multiprocessing.

Then it needs to be implemented correctly so it doesn't swallow errors like before.

I do think that you could cut down the time that `calculate_coverage` takes currently by 10x or so just by using `pandas` instead of hand processing it.

But the priority is always _correct first, robust second, fast if possible_.

**Comment by psj1997** [comment]
I have tried with pandas before, but it not save much time. So I still want to use multiprocess and I will try to fix the questions here.

**Comment by luispedro** [comment]
I'm not against it, but be mindful of what the priorities are. We can submit the manuscript even if the tool does not use multiple threads in this one step, but we cannot submit it if the tool crashes on paths with spaces or swallows the correct error message.

**Comment by luispedro** [comment]
Can you please merge https://github.com/BigDataBiology/SemiBin/pull/22/commits/f8d17993bf8a4f85893529da76936a24a36ddd47 even if you don't want the other commit?

(Partially my fault for mixing it here instead of a separate PR)

**Comment by psj1997** [comment]
Yeah. I will merge it later.

**Pull request closed without merging**
